### ISSUE TITLE
DXF for mounting plate/ french cleats?

### ISSUE THREAD

**Issue by voron69-bit** [Makerr-Studio/CentrifugalDustSeparator-#13]
Any chance you'd be willing to share those files as well? Even if you don't have a CNC, they are useful for layouts to make by hand.

Thank You! I can't wait to see your next videos!

**Comment by Makerr-Studio** [comment]
In the folder [MK2_EU](https://github.com/Makerr-Studio/CentrifugalDustSeparator-/tree/main/MK2_EU) I added the Shaper files (and also the DXF's) and the Fusion files of the baseplate and cleat.
