### ISSUE TITLE
Please add Full CAD Files for the EU Version

### ISSUE THREAD

**Issue by Leo-Wolf-the-Engineer** [Makerr-Studio/CentrifugalDustSeparator-#18]
Hi, 

could you add the CAD files (STEP or Fusion) of the complete assembly for the EU Version? 
I need those for further planning.

Thank you
Leo

**Comment by Makerr-Studio** [comment]
You can download the complete STEP-file on my Patreon. It's a free product for all my supporters.

https://www.patreon.com/CapturingDust/shop/complete-step-file-mk2-eu-720835
