### ISSUE TITLE
Tube sourcing links

### ISSUE THREAD

**Issue by 3dtrix** [Makerr-Studio/CentrifugalDustSeparator-#20]
Hi, 

in Germany i buy my tubes from this online shop:

Original Plexiglas manufacture:
150mm / 3mm
https://www.plexiglas-shop.com/de/produkte/ro0a070gt.html

They ship to EU incl. UK

cheers 
Carsten

**Comment by Makerr-Studio** [comment]
Thx for sharing! I added it to the EU and UK build versions.

**Comment by Makerr-Studio** [comment]
Thx for sharing! I added it to the EU and UK build versions.
