### ISSUE TITLE
Why mirror the impeller?

### ISSUE THREAD

**Issue by philreindl** [Makerr-Studio/CentrifugalDustSeparator-#3]
In the interest of keeping parts count low, it would be nice if both extractor tubes were identical.  I am curious whether there is a functional advantage to having one of the impellers mirrored.  

Thanks for this awesome project!

**Comment by Makerr-Studio** [comment]
The Mirrored impellers is just for visual. You can make the both separators the same, without loss of efficiency. (Not tested, only that is what I think :D)
