### ISSUE TITLE
Y-Inlet requires supports

### ISSUE THREAD

**Issue by philreindl** [Makerr-Studio/CentrifugalDustSeparator-#4]
The Y inlet and Y outlet parts have bosses on them which require supports.  If the top boss was removed and the lettering embossed directly on the wall of the Y that would cut the supports in half.  If the bracket interface boss were to have a chamfer around the outside that would greatly reduce the supports needed there as well.

Thank you for this amazing work!

**Comment by Makerr-Studio** [comment]
I see ware you going! It will reduce about 3 hours off printing time on the Inlet alone when we are able to print without supports.

When I have some time I will try to find a way to eliminate all the supports by using chamfers, or relocate the bracket interface.

**Comment by Makerr-Studio** [comment]
@philreindl I just added the REV2 files of the Y-pieces + brackeds. They need less material to print now by removing the needs for support thanks to your tip!
