### ISSUE TITLE
tube length

### ISSUE THREAD

**Issue by philreindl** [Makerr-Studio/CentrifugalDustSeparator-#8]
I bought the 6"x36" tube listed on the parts list, assuming it would be cut into two parts.  But looking at the plan, am I reading it right that we are to cut that into 500mm long segments?
500mm is 19.7", which of course is more than half of 36"

I have printed the parts for the original mk2 files.

Thanks
Phil

**Comment by Makerr-Studio** [comment]
I had the same thoughts on that. I used around the same length that Tim from Pilson Guitars used in his version. Only the offcut is a lot! I did not gamble on it and ordered 2 tubes and kept the same size and rounded it out on mm.

In my tests so far I think you can do with a bit less length and use the 18”. So you only need one tube. Don’t know how much it effects performance.

**Comment by philreindl** [comment]
Hrm.  I wonder how much it would matter.  My biggest concern is that the airflow would be significantly reduced using the long-cone as designed.  The long-cone intrudes into the mouth of the outlet by about an inch, which would reduce the open area of the outlet considerably.  Maybe with a shorter long cone it would be fine.

**Comment by Makerr-Studio** [comment]
Next week I can adjust the size for you if that would help!

**Comment by philreindl** [comment]
Might be worth adding to the experimental files section.  My son has a science fair coming up, maybe this is a worthy experiment he can do for me

**Comment by Makerr-Studio** [comment]
@philreindl 
I reduced the length by 1.6 inch. Step-file is in the folder:
https://github.com/Makerr-Studio/CentrifugalDustSeparator-/tree/main/MK2/NOT%20TESTED%20-%20REQUESTED%20PARTS

**Comment by philreindl** [comment]
awesome, thanks!
